### ISSUE TITLE
Cannot override locale :it

### ISSUE THREAD

**Issue by RandieM** [damoiser/qr-bills#2]
Hello there. Thanks for making this gem available; it is very much needed.

I have a question about locales. I see that you set the locale/language to :it in two places in your code; one is in qr-params.rb with `language: "it",` and the other one is in qr-bills.rb, where it is passed as the default locale `I18n.default_locale = :it`. The problem is that I cannot seem to be able to override this locale, unless I comment out the code from qr-bills.rb. Am I missing something?

Ideally, wouldn't the default locale be set in a configuration file, though, instead of the code?

**Comment by damoiser** [comment]
Hello there, thanks and good to see that this work is helping someone out there ;-)

You have right, my first idea was to use the ```qr_params``` to set dynamically the language (```get_qr_params[:bill_params][:language]```), however I miss to read that value later on. I only used the italian language for this, then I didn't noticed yet a bug.

Did you already tried to set on your app default value for I18n? I would expect that something like that should work and override the value in the gems as well:
```
config.i18n.default_locale = :en
```

Otherwise I will take a look a bit more deeper on that and try to find a solution.

**Comment by damoiser** [comment]
FYI @RandieM thanks of the PR of @alexanderadam this issue should be resolved

**Comment by RandieM** [comment]
Apologies for the (very) late reply. Just confirming that the problem has indeed been fixed.
